import { Arrays } from '../mod.ts';

import {
    assert,
    assertEquals,
    Test,
    testGroup,
} from './deps.ts';

testGroup('Arrays',
    testGroup('splitAt',
        testGroup('array = [1, 2, 3]',
            new Test('n = 0', () => assertEquals(Arrays.splitAt(0, [1, 2, 3]), [[], [1, 2, 3]])),
            new Test('n=1', () => assertEquals(Arrays.splitAt(1, [1, 2, 3]), [[1], [2, 3]])),
            new Test('n=2 (last index of array)', () => assertEquals(Arrays.splitAt(2, [1, 2, 3]), [[1, 2], [3]])),
            new Test('n=3 (size of array)', () => assertEquals(Arrays.splitAt(3, [1, 2, 3]), [[1, 2, 3], []])),
        ),
    ),
    testGroup('isNonEmpty',
        new Test('empty array is not non-empty', () => assert(!Arrays.isNonEmpty([]))),
        new Test('non-empty array is non-empty', () => assert(Arrays.isNonEmpty([1]))),
    ),
    testGroup('head',
        new Test('singleton array', () => assertEquals(Arrays.head([1]), 1)),
        new Test('multi-element array', () => assertEquals(Arrays.head([[2, 3], [4]]), [2, 3])),
    ),
    testGroup('tail',
        new Test('singleton array', () => assertEquals(Arrays.tail([1]), [])),
        new Test('multi-element array', () => assertEquals(Arrays.tail([1, 2, 3]), [2, 3])),
    ),
    testGroup('headDeep',
        new Test('flat array', () => assertEquals(Arrays.headDeep([1, 2, 3]), 1)),
        new Test('nested array (1 level)', () => assertEquals(Arrays.headDeep([[2, 3], 4]), 2)),
        new Test('nested array (3 levels)', () => assertEquals(Arrays.headDeep([[[[2], [3]]], 4]), 2)),
    ),
    testGroup('flatten',
        new Test('empty array', () => assertEquals(Arrays.flatten([]), [])),
        new Test('flat array', () => assertEquals(Arrays.flatten([1, 2, 3]), [1, 2, 3])),
        new Test('nested array (1 level)', () => assertEquals(Arrays.flatten([[2, 3], 4]), [2, 3, 4])),
        new Test('nested array (3 levels)', () => assertEquals(Arrays.flatten([[[[2], [3]]], 4]), [2, 3, 4])),
    ),
    testGroup('replace',
        new Test('the returned list is not the same array object', () => {
            const arr = [1, 2, 3];
            assert(arr !== Arrays.replace(arr, -1, 0));
        }),
        new Test('empty array', () => assertEquals(Arrays.replace([], 0, 0), [])),
        new Test('i >= length', () => assertEquals(Arrays.replace([1, 2, 3], 3, 0), [1, 2, 3])),
        new Test('i < 0', () => assertEquals(Arrays.replace([1, 2, 3], -1, 0), [1, 2, 3])),
        new Test('element at start of array', () => assertEquals(Arrays.replace([1, 2, 3], 0, 0), [0, 2, 3])),
        new Test('element in middle of array', () => assertEquals(Arrays.replace([1, 2, 3], 1, 0), [1, 0, 3])),
        new Test('element at end of array', () => assertEquals(Arrays.replace([1, 2, 3], 2, 0), [1, 2, 0])),
        testGroup('range',
            new Test('whole array', () => assertEquals(Arrays.replace([1, 2, 3], [0, 2], 0), [0])),
            new Test('min < 0, max > size of array', () => assertEquals(Arrays.replace([1, 2, 3], [-1, 3], 0), [0])),
            new Test('part of array', () => assertEquals(Arrays.replace([1, 2, 3, 4], [1, 2], 0), [1, 0, 4])),
            new Test('max < min', () => assertEquals(Arrays.replace([1, 2, 3, 4], [2, 1], 0), [1, 2, 3, 4])),
        ),
    ),
).runAsMain();
